### ISSUE TITLE
Playing the video in background while activity is stopped

### ISSUE THREAD

**Issue by abelhamilton** [PierfrancescoSoffritti/android-youtube-player#326]
Hello, thanks again for this wonderful library!

Maybe I'm missing something but the player continues playing in the background when I press the home button or open another activity. It happens sometimes only when the video is not loaded yet even when mYouTubePlayer.pause(); is called in the onPause method.

Here is what I do :
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video);
        ButterKnife.bind(this);

        mVideo = (Video) getIntent().getSerializableExtra(Constant.INTENT_OBJECT);
        mVideoActivity = (VideoAct) getIntent().getSerializableExtra(Constant.INTENT_ACTIVITY);

        initYoutubePlayer();
    }

private void initYoutubePlayer() {
        getLifecycle().addObserver(youtubePlayerView);
        youtubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                mYouTubePlayer = youTubePlayer;
                int startTime = 0;
                if (mVideoActivity != null) {
                    startTime = mVideoActivity.timeCode;
                }
                YouTubePlayerUtils.loadOrCueVideo(mYouTubePlayer, getLifecycle(), videoKey, startTime);
            }
        });
}

@Override
public void onPause() {
    super.onPause();
    if (mYouTubePlayer != null) {
       mYouTubePlayer.pause();
    }
}

@Override
protected void onDestroy() {
    super.onDestroy();
    youtubePlayerView.release();
}
```
Thanks in advance

**Comment by PierfrancescoSoffritti** [comment]
mmm this snippet looks good, you actually don't need to override onPause and onDesotry, but that's not the issue.

Are these the only places where you're using `mYouTubePlayer`?

I need more details to understand what's wrong.

**Comment by abelhamilton** [comment]
Yes, that's the only places where I'm using `mYouTubePlayer`.
I'm using : implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.1'

It happens quite randomly when I quit when the youtube logo is about to appear or have just appeared and the video is still loading.

Which other details can I give you?

**Comment by PierfrancescoSoffritti** [comment]
Are you using the player in a Fragment or in an Activity?
Is there any way you can create a simple app where you replicate the issue? Only if we can replicate it we can fix it.

I never encountered this issue (but since you're saying it happens every once in a while I may just have not noticed it), you could try checking the sample app to be sure you're doing everything in the same way.

**Comment by abelhamilton** [comment]
Iunderstand and I'll create a sample app later today.
I'm using it in an activity and I already checked multiple times the sample app.

**Comment by PierfrancescoSoffritti** [comment]
uhm ok. Let me know if you can replicate it, I'll be happy to look at the code!

**Comment by abelhamilton** [comment]
Here is a sample app where I can reproduce it, tested on Samsung Galaxy note 3 and Android 5.0
[MyApplication.zip](https://github.com/PierfrancescoSoffritti/android-youtube-player/files/2988696/MyApplication.zip)

**Comment by abelhamilton** [comment]
I also just tested your sample app with the basic example and I can reproduce it too.
So maybe my sample app will not be very useful after all :p

**Comment by PierfrancescoSoffritti** [comment]
You're right, it seems like if you leave the app just after `loadVideo` is called it keeps playing. I'll fix the bug during the weekend. thank you for reporting it!

**Comment by PierfrancescoSoffritti** [comment]
Bug fixed in version 10.0.2! thank you for the help :)

**Comment by abelhamilton** [comment]
No, thank YOU for your help.
I can't reproduce it anymore! :)

**Comment by spapapan** [comment]
> Bug fixed in version 10.0.2! thank you for the help :)

I am still facing this issue and I am using 10.0.5. It's exactly how abelhamilton described it. Sometimes the video plays even though the entire app is in the background. I need to kill the app to make the video stop because there is no other way. 

I have an [app](https://play.google.com/store/apps/details?id=com.app.babyapp) already uploaded to the Play Store if you wish to check it by yourself.
