### ISSUE TITLE
onReady is never being called.

### ISSUE THREAD

**Issue by R01NDev** [PierfrancescoSoffritti/android-youtube-player#388]
Hello, I created the fragment exampleFragment that was in the repo but I'm having an issue where the player never gets to the onReady state. 

      private void initYouTubePlayerView() {
       
        getLifecycle().addObserver(youTubePlayerView);

        youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                String data = getArguments().getString("url");
                int off = getArguments().getInt("offset");
                int pos = getArguments().getInt("pos");

                YouTubePlayerUtils.loadOrCueVideo(
                        youTubePlayer, getLifecycle(),
                        data,0
                );

            }

The player reaches getLifecycle().addObserver(youTubePlayerView); but never onReady.
I can see the player there when I can click on a video and it just keeps spinning endlessly since I'm guessing it has no video data to play.
What could be the cause of this? Do you need more code snipets?

Thank you for your awesome project btw and regards.

**Comment by R01NDev** [comment]
After 2 days of frustration. This is an emulator bug, the player never gets in a ready state on android TV emu.

**Comment by PierfrancescoSoffritti** [comment]
Hey, that's strange. I'll try to have a look!

**Comment by KumarVelu** [comment]
@Eliasdevlb , I am facing the same problem in android tv emulator. 
Did you find a fix or any workaround ?

**Comment by yasandev** [comment]
> I am facing the same problem on android real devices but is not happening all the time @PierfrancescoSoffritti Can reopen this issue?
Same. It is only happening to one real device that I know.

**Comment by roelvogel** [comment]
I'm having this issue on real devices too, is there anyone that solves this?

**Comment by RahulRaviandroid** [comment]
I am having this issue on real device , sometimes onReady method are not being called . Any one who has solved this issues ??

**Comment by yasandev** [comment]
> I am having this issue on real device , sometimes onReady method are not being called . Any one who has solved this issues ??

I have not used this library for the past few months but I did manage to fix it. The "fix" does not make much sense, unfortunately. I literally did a very very small refactor + moved the code into another file. Somehow it fixed it and we never experienced this issue again.

So basically you just have to try different ways of using the library etc and on some specific special configurations, it does not have this issue.

**Comment by PierfrancescoSoffritti** [comment]
what version of the library are you using? you should use 11.1.0, as #830 has been fixed there.

**Comment by yasandev** [comment]
I no longer work with this library and when I did, this release was not published yet. I had seen that change on the changelog but assumed it's still not fixed because of @RahulRaviandroid's comment.
